### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by skarampatakis** [okgreece/the-accountant#2]
after build, I get the following error

```
Error: [$injector:unpr] Unknown provider: eProvider <- e <- web
http://errors.angularjs.org/1.6.5/$injector/unpr?p0=eProvider%20%3C-%20e%20%3C-%20web
Stack trace:
r/<@http://theaccountant.okfn.gr/app/main-c6de5493863724c98200.js:61:571
dt/x.$injector<@http://theaccountant.okfn.gr/app/main-c6de5493863724c98200.js:61:23135
r@http://theaccountant.okfn.gr/app/main-c6de5493863724c98200.js:61:22044
dt/$<@http://theaccountant.okfn.gr/app/main-c6de5493863724c98200.js:61:23218
r@http://theaccountant.okfn.gr/app/main-c6de5493863724c98200.js:61:22044
i@http://theaccountant.okfn.gr/app/main-c6de5493863724c98200.js:61:22349
a@http://theaccountant.okfn.gr/app/main-c6de5493863724c98200.js:61:22570
i/<@http://theaccountant.okfn.gr/app/main-c6de5493863724c98200.js:61:20786
a@http://theaccountant.okfn.gr/app/main-c6de5493863724c98200.js:61:22674
dt/$<@http://theaccountant.okfn.gr/app/main-c6de5493863724c98200.js:61:23238
r@http://theaccountant.okfn.gr/app/main-c6de5493863724c98200.js:61:22044
i@http://theaccountant.okfn.gr/app/main-c6de5493863724c98200.js:61:22349
a@http://theaccountant.okfn.gr/app/main-c6de5493863724c98200.js:61:22570
Tt/this.$get</</<@http://theaccountant.okfn.gr/app/main-c6de5493863724c98200.js:61:49536
h@http://theaccountant.okfn.gr/app/main-c6de5493863724c98200.js:61:36307
a@http://theaccountant.okfn.gr/app/main-c6de5493863724c98200.js:61:32531
H/<@http://theaccountant.okfn.gr/app/main-c6de5493863724c98200.js:61:32048
compile/<@http://theaccountant.okfn.gr/app/main-c6de5493863724c98200.js:56:93321
Y/<@http://theaccountant.okfn.gr/app/main-c6de5493863724c98200.js:61:6121
Se@http://theaccountant.okfn.gr/app/main-c6de5493863724c98200.js:61:44660
h@http://theaccountant.okfn.gr/app/main-c6de5493863724c98200.js:61:37004
a@http://theaccountant.okfn.gr/app/main-c6de5493863724c98200.js:61:32531
H/<@http://theaccountant.okfn.gr/app/main-c6de5493863724c98200.js:61:32048
re/<@http://theaccountant.okfn.gr/app/main-c6de5493863724c98200.js:61:34947
y@http://theaccountant.okfn.gr/app/main-c6de5493863724c98200.js:56:95323
v@http://theaccountant.okfn.gr/app/main-c6de5493863724c98200.js:56:94861
c@http://theaccountant.okfn.gr/app/main-c6de5493863724c98200.js:56:61432
e/this.sync@http://theaccountant.okfn.gr/app/main-c6de5493863724c98200.js:56:61452
a@http://theaccountant.okfn.gr/app/main-c6de5493863724c98200.js:56:58338
d</e.prototype.invokeHook@http://theaccountant.okfn.gr/app/main-c6de5493863724c98200.js:56:23593
d</e.runSynchronousHooks@http://theaccountant.okfn.gr/app/main-c6de5493863724c98200.js:56:24435
s@http://theaccountant.okfn.gr/app/main-c6de5493863724c98200.js:56:17886
u@http://theaccountant.okfn.gr/app/main-c6de5493863724c98200.js:61:71021
l/<@http://theaccountant.okfn.gr/app/main-c6de5493863724c98200.js:61:71426
$digest@http://theaccountant.okfn.gr/app/main-c6de5493863724c98200.js:61:77123
$evalAsync/<@http://theaccountant.okfn.gr/app/main-c6de5493863724c98200.js:61:78747
i@http://theaccountant.okfn.gr/app/main-c6de5493863724c98200.js:61:24578
yt/l.defer/n<@http://theaccountant.okfn.gr/app/main-c6de5493863724c98200.js:61:26042
 <ui-view class="ng-scope" data-ng-animate="1">
```

It probably happens because of minification.

The problem does not occur on master branch

**Comment by skarampatakis** [comment]
The problem does not occur also on the dev server. Just after build task. Could we somehow turn off minification temporally?

**Comment by skarampatakis** [comment]
Fixed this temporaly on https://github.com/okgreece/the-accountant/commit/b432b4483844cb415f8615e275ebc77b090f2415

I turned off minification plugin. At least now it builds and I managed to set it up on the server, but should be fixed some how. 
Please @ventouris @larjohn have a look when available.

**Comment by ventouris** [comment]
I have the same issue in another Angular project. It is related with the Webpack. I read in different sources that you need to update to the latest version, but it wasn't fixed for me, so I ended up without minification too.

**Comment by skarampatakis** [comment]
What I have found was 
https://stackoverflow.com/questions/20604469/unknown-provider-e-provider-error-while-using-angularjs-and-ruby-on-rails

and I suspect it is that line
https://github.com/okgreece/the-accountant/commit/d3e1824eba6606f507331da0a3391170a8276e01#diff-e57206bb15883002b399a5f5bf436764R10

but just guessing
